---
abstract: 'Perl extension for handling MODS records'
author:
  - 'Patrick <patrick.hochstenbach@ugent.be>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MODS-Record
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  JSON: 0
  Moo: 0
  Test::More: 0
  XML::Parser: 0
version: 0.02
